#!/bin/bash

. ./bashlib

Locking=`param name`

head

if [ ! -e ./locked ];then
    if [ "$Locking" != "" ];then
        echo $Locking > ./locked
        echo "OK lock $Locking"
    else 
        echo "FAILED please input locked name"
    fi
else
    Locked=`cat ./locked`
    echo "FAILED already locked by $Locked"
fi

rear
