#!/bin/bash

. ./bashlib

UnlockName=`param name`

head

if [ ! -e ./locked ];then
    echo "FAILED unlock $UnlockName"
else
    Locked=`cat ./locked`
    if [ "$Locked" == "$UnlockName" ];then
        rm -rf ./locked
        echo "OK unlock $UnlockName"
    else
        echo "FAILED already locked by $Locked"
    fi
fi

rear


