#!/bin/sh

. ./commonScript

head

disconnectUserName=`parse name $QUERY_STRING`

if [ ! -e ./connectStatus ];then
    echo -e "FAILED\nplz connect first"
else
    connectStatus=`cat ./connectStatus`
#    echo $connectStatus
#    echo "${connectStatus%%,*} == $disconnectUserName"    
    if [ "${connectStatus%%,*}" == "$disconnectUserName" ];then
        rm -rf ./connectStatus
        echo -e "FINISH\n$disconnectUserName"
    else
        printConnectStatus
    fi
fi

rear


