#!/bin/sh

. /var/www/commonScript

if [ "$QUERY_STRING" != "" ];
then
    head
    PORT=`parse port $QUERY_STRING`
else
    PORT=$1
fi

if [ "$PORT" == "" ];then
    echo FAILED
    echo example:
    echo http://127.0.0.1/setport?port=8080
else
    modify_key_value port $PORT ../../etc/thttpd.d/thttpd.conf
    killall thttpd
    ../../usr/bin/thttpd -C ../../etc/thttpd.d/thttpd.conf &
fi
