#!/bin/sh

. ./commonScript

head

connectName=`parse name $QUERY_STRING`

if [ ! -e ./connectUser ];then
    if [ "$connectName" != "" ];then
        echo $connectName > ./connectUser
        echo -e "FINISH\nconnect $connectName"
    else
        echo -e "FAILED\nplease input connect name"
    fi
else
    connectUser=`cat ./connectUser`
    echo -e "FAILED\nalready connect by $connectUser"
fi

rear
