#!/bin/sh

. ./commonScript

head

disconnectUserName=`parse name $QUERY_STRING`

if [ ! -e ./connectUser ];then
    echo -e "FAILED\nplz connect first"
else
    connectUser=`cat ./connectUser`
    if [ "$connectUser" == "$disconnectUserName" ];then
        rm -rf ./connectUser
        echo -e "FINISH\ndisconnect $disconnectUserName"
    else
        echo -e "FAILED\nalready connect by $connectUser"
    fi
fi

rear


