#!/bin/sh
EXAMPLE=http://127.0.0.1/outputDA?dig=0x10,0x11,0x12,0x13,0x14-0x20,0x21,0x22,0x23,0x24-0x30,0x31,0x32,0x33,0x34-0x40,0x41,0x42,0x43,0x44-0x50,0x51,0x52,0x53,0x54-0x60,0x61,0x62,0x63,0x64
#gettimeofday "controlCPAP" "script"

. /var/www/commonScript


if [ "$QUERY_STRING" != "" ];
then
    head
else
    QUERY_STRING=$1
fi

DIG_ARRAY=`parse dig $QUERY_STRING`

if [ -z $DIG_ARRAY ];then
    echo FAILED
    echo example:
    echo $EXAMPLE
else

    arr=$(echo $DIG_ARRAY | tr ";" "\n")

    if [ -z "$(pidof cpap2psg)" ]
    then
        /nand2/root/usr/bin/cpap2psg &
        sleep 1
    fi

#    BINARY_STRING=`echo $x | sed 's/,//g' | sed 's/0x/\\x/g'`
    
    ch=0
    for x in $arr
    do    
        echo "$x" > /tmp/FIFO_CHANNEL$ch
        ch=$((ch+1))
    done

    echo "OK"

fi

