#!/bin/sh

#
#setip?ip=fixip,192.168.0.1,255.255.255.0,192.168.0.254
#

. /var/www/commonScript


if [ "$QUERY_STRING" != "" ];
then
    head
    SHELL_CMD=`parse config $QUERY_STRING`
else
    SHELL_CMD=$1
fi


#fixip/dhcp,$IP , $MASK , $GW , $Hostname , $Port , $MAC
####################################
#    Parse TYPE,IP,Gateway,Mask
####################################
TYPE=`echo $SHELL_CMD | cut -d',' -f1`
IP=`echo $SHELL_CMD | cut -d',' -f2`
GW=`echo $SHELL_CMD | cut -d',' -f3`
MASK=`echo $SHELL_CMD | cut -d',' -f4`
HOST=`echo $SHELL_CMD | cut -d',' -f5`
PORT=`echo $SHELL_CMD | cut -d',' -f6`
MAC=`echo $SHELL_CMD | cut -d',' -f7`

if [ "$SHELL_CMD" == "" ];then
    echo FAILED
    echo example:
    echo http://127.0.0.1/setip?ip=setip?ip=fixip,192.168.0.1,255.255.255.0,192.168.0.254
else

#set ip
    if [ "$TYPE" == "fixip" ]
    then
        echo SUCCESS
        ifconfig eth0 $IP netmask $MASK up
        route add default gw $GW
        ifconfig
        
        echo "NetworkType=$TYPE" > /nand2/root/etc/network.conf
        echo "ip=$IP" >> /nand2/root/etc/network.conf 
        echo "gateway=$GW" >> /nand2/root/etc/network.conf
        echo "netmask=$MASK" >> /nand2/root/etc/network.conf
        
    else
        echo "NetworkType=$TYPE" > /nand2/root/etc/network.conf
    fi

#set host
    echo "netbios name=$HOST" > ../../etc/netbios_name.conf

#set port
    modify_key_value port $PORT ../../etc/thttpd.d/thttpd.conf

#set mac
    cd /nand2/root/sh
    ./setmac.sh $MAC > /dev/null

    echo OK
    
    sync;sync;sync

    reboot
fi
