#!/bin/sh

. /var/www/commonScript

if [ "$QUERY_STRING" != "" ];
then
    head
    HOST=`parse host $QUERY_STRING`
else
    HOST=$1
fi

if [ "$HOST" == "" ];then
    echo FAILED
    echo example:
    echo http://127.0.0.1/sethost?host=sigbox1
else
    echo OK
    echo "netbios name=$HOST" > ../../etc/netbios_name.conf
    killall nmbd
    ../../usr/bin/nmbd -D
    ../../usr/bin/smbd -D
fi
